const books = {
    journey:        { title: "Journey to the End of the Night",                     author: "Louis-Ferdinand Céline",  read: false, comments: "Céline’s masterpiece―colloquial, polemic, hyper realistic―boils over with bitter humor and revulsion at society’s idiocy and hypocrisy: Journey to the End of the Night is a literary symphony of cruelty and violence that hurtles through the improbable travels of the petit bourgeois (and largely autobiographical) antihero, Bardamu: from the trenches of WWI, to the African jungle, to New York, to the Ford Factory in Detroit, and finally to life in Paris as a failed doctor. Ralph Manheim’s pitch-perfect translation captures Céline’s savage energy, and a dynamic afterword by William T. Vollmann presents a fresh, furiously alive take on this astonishing novel." },
    whyreadcalvino: { title: "Why Read The Classics?",            author: "Italo Calvino", read: false, comments: "Classics, according to Italo Calvino, are not only works of enduring cultural value, but also personal touchstones. They are the books we are always rereading in order to understand our world and ourselves. Here, Calvino introduces more than thirty works from his own ideal library in essays of warmth, humor, and striking insight. He discusses great authors ranging from Homer to Jorge Luis Borges, and from Charles Dickens to the Persian folklorist Nezami. Whether tracing the links between Ovid's Metamorphoses and Alain Robbe-Grillet's objectivity, discovering the origins of science fiction in the writings of Cyrano de Bergerac, or convincing us that the Italian novelist Carlo Emilio Gadda's works are like artichokes, Calvino offers a new perspective on beloved favorites and introduces us to hidden gems."},
    kafkamurakami:  { title: "Kafka On The Shore",            author: "Haruki Murakami",  read: false, comments: "Here we meet fifteen-year-old runaway Kafka Tamura and the elderly Nakata, who is drawn to Kafka for reasons that he cannot fathom. As their paths converge, acclaimed author Haruki Murakami enfolds readers in a world where cats talk, fish fall from the sky, and spirits slip out of their bodies to make love or commit murder, in what is a truly remarkable journey." },
    gogol:          { title: "Dead Souls",                       author: "Nikolai Gogol",  read: false, comments: "Since its publication in 1842, Dead Souls has been celebrated as a supremely realistic portrait of provincial Russian life and as a splendidly exaggerated tale; as a paean to the Russian spirit and as a remorseless satire of imperial Russian venality, vulgarity, and pomp. As Gogol's wily antihero, Chichikov, combs the back country wheeling and dealing for 'dead souls'--deceased serfs who still represent money to anyone sharp enough to trade in them--we are introduced to a Dickensian cast of peasants, landowners, and conniving petty officials, few of whom can resist the seductive illogic of Chichikov's proposition. " },
    stronghold:     { title: "The Stronghold",                  author: "Dino Buzzati",  read: true, comments: "At the start of Dino Buzzati’s The Stronghold, newly commissioned officer Giovanni Drogo has just received his first posting: the remote Fortezza Bastiani. North of this stronghold are impassable mountains; to the south, a great desert; and somewhere out there is the enemy, whose attack is imminent. This is the enemy that Lieutenant Drogo has been sent to draw out of his lair, to defeat once and for all, returning home in triumph. And yet time passes, and where is the enemy? As the soldiers in the fortress await the foretold day of reckoning, they succumb to inertia, and though death occurs, it is not from bravery. Decades pass. A lifetime passes. Drogo, however, still has his lonely vigil to keep." },
    bewareofpity:   { title: "Beware of Pity",              author: "Stefan Zweig",  read: false, comments: "Hofmiller, an Austro-Hungarian cavalry officer stationed at the edge of the empire, is invited to a party at the home of a rich local landowner, a world away from the dreary routine of the barracks. The surroundings are glamorous, wine flows freely, and the exhilarated young Hofmiller asks his host's lovely daughter for a dance, only to discover that sickness has left her painfully crippled. It is a minor blunder that will destroy his life, as pity and guilt gradually implicate him in a well-meaning but tragically wrongheaded plot to restore the unhappy invalid to health." },
    thedoor:        { title: "The Door",                    author: "Magda Szabo",  read: false, comments: "The Door is an unsettling exploration of the relationship between two very different women. Magda is a writer, educated, married to an academic, public-spirited, with an on-again-off-again relationship to Hungary’s Communist authorities. Emerence is a peasant, illiterate, impassive, abrupt, seemingly ageless. She lives alone in a house that no one else may enter, not even her closest relatives. She is Magda’s housekeeper and she has taken control over Magda’s household, becoming indispensable to her. And Emerence, in her way, has come to depend on Magda. They share a kind of love—at least until Magda’s long-sought success as a writer leads to a devastating revelation." },
    blackwings:     { title: "Black Wings Has My Angel",                 author: "Elliott Chaze",  read: false, comments: "When Tim Sunblade escapes from prison, his sole possession is an infallible plan for the ultimate heist. Trouble is it’s a two-person job. So when he meets Virginia, a curiously well-spoken “ten-dollar tramp,” and discovers that the only thing she cares for is “drifts of money, lumps of it,” he knows he’s met his partner. What he doesn’t suspect is that this lavender-eyed angel might just prove to be his match. " },
    berlin:         { title: "Berlin Alexanderplatz",                      author: "Alfred Döblin",  read: false, comments: "Berlin Alexanderplatz, the great novel of Berlin and the doomed Weimar Republic, is one of the great books of the twentieth century—gruesome, farcical, and appalling, word-drunk, pitch-dark. In Michael Hofmann's extraordinary new translation, Alfred Döblin's masterpiece lives in English for the first time." },
    stoner: { title: "Stoner", author: "John Williams", read: false, comments: "William Stoner is born at the end of the nineteenth century into a dirt-poor Missouri farming family. Sent to the state university to study agronomy, he instead falls in love with English literature and embraces a scholar’s life, so different from the hardscrabble existence he has known. And yet as the years pass, Stoner encounters a succession of disappointments: marriage into a “proper” family estranges him from his parents; his career is stymied; his wife and daughter turn coldly away from him; a transforming experience of new love ends under threat of scandal. Driven ever deeper within himself, Stoner rediscovers the stoic silence of his forebears and confronts an essential solitude." },
    granta:         { title: "Granta, Volume 129: Fate",                      author: "Multiple Authors",  read: false, comments: "Granta 129 brings you twenty-two meditations on fate in all its many forms. From Joseph Roth's reflection on Sarajevo in the wake of the First World War to Cynthia Ozick's exploration of the limits of belief, this issue stretches our understanding of fate, both in fact and in fiction. " },
    kokoro:         { title: "Kokoro",                      author: "Natsume Soseki",  read: false, comments: "Sensei, a man seen against the rich background of old Japan entering the modern era, is outwardly successful. He has position, wealth, a charming wife. But deep in the heart of things, he is harried with a profound sense of isolation whose cure lies only in 'faith, madness, or death.' His long-hidden secret, divulged to a young friend who faces a similar dilemma, is told with mounting intensity. Sensei confesses the crime of his young manhood, a crime in which, with all the appearance of innocence, he destroyed his best friend, the woman he loved—and himself." },
    baldwin:        { title: "Giovanni's Room",                     author: "James Baldwin",  read: false, comments: "In 1950s Paris, a young American expatriate finds himself caught between his repressed desires and conventional morality. David has just proposed marriage to his American girlfriend, but while she is away on a trip he becomes involved in a doomed affair with a bartender named Giovanni. With sharp, probing insight, James Baldwin’s classic novel delves into the mysteries of love and tells a deeply moving story that reveals the unspoken complexities of the human heart." },
    labyrinth:      { title: "Labyrinths",                   author: "Jorge Luis Borges",  read: true, comments: "The groundbreaking trans-genre work of Argentinian writer Jorge Luis Borges (1899-1986) has been insinuating itself into the structure, stance, and very breath of world literature for well over half a century. Multi-layered, self-referential, elusive, and allusive writing is now frequently labeled Borgesian. Umberto Eco's international bestseller, The Name of the Rose, is, on one level, an elaborate improvisation on Borges' fiction 'The Library,' which American readers first encountered in the original 1962 New Directions publication of Labyrinths." },
    mao2:           { title: "Mao II",                      author: "Don DeLillo",  read: false, comments: "Bill Gray, a famous, reclusive novelist, emerges from his isolation when he becomes the key figure in an event staged to force the release of a poet hostage in Beirut. As Bill enters the world of political violence, a nightscape of Semtex explosives and hostages locked in basement rooms, his dangerous passage leaves two people stranded: his brilliant, fixated assistant, Scott, and the strange young woman who is Scott’s lover—and Bill’s." },
    oconnor:        { title: "The Complete Stories",                    author: "Flannery O'Connor",  read: false, comments: "In these sly, laconic, and fiercely observed works, O’Connor does nothing less than elaborate a unique and new way of seeing the world. Contorting her sharply drawn characters through her Southern Gothic prism, she produces a panorama unequaled in its vision of the interplays of faith, evil, humor, violence, and compassion that embody American life." },
    ress:           { title: "Resurrection",                        author: "Leo Tolstoy",  read: false, comments: "Serving on the jury at a murder trial, Prince Dmitri Nekhlyudov is devastated when he sees the prisoner - Katyusha, a young maid he seduced and abandoned years before. As Dmitri faces the consequences of his actions, he decides to give up his life of wealth and luxury to devote himself to rescuing Katyusha, even if it means following her into exile in Siberia. But can a man truly find redemption by saving another person? Tolstoy's most controversial novel, Resurrection (1899) is a scathing indictment of injustice, corruption and hypocrisy at all levels of society. Creating a vast panorama of Russian life, from peasants to aristocrats, bureaucrats to convicts, it reveals Tolstoy's magnificent storytelling powers. Anthony Briggs' superb new translation preserves Tolstoy's gripping realism and satirical humour. In his introduction, Briggs discusses the true story behind Resurrection, Tolstoy's political and religious reasons for writing the novel, his gift for characterization and the compelling psychological portrait of Dmitri. This edition also includes a chronology, notes and a summary of chapters." },
    dunces:         { title: "A Confederacy of Dunces",     author: "John Kennedy Toole",  read: false, comments: "A Confederacy of Dunces is an American comic masterpiece. John Kennedy Toole's hero, one Ignatius J. Reilly, is 'huge, obese, fractious, fastidious, a latter-day Gargantua, a Don Quixote of the French Quarter. His story bursts with wholly original characters, denizens of New Orleans' lower depths, incredibly true-to-life dialogue, and the zaniest series of high and low comic adventures' (Henry Kisor, Chicago Sun-Times)." },
    dance:          { title: "Dance Dance Dance",                       author: "Haruki Murakami",  read: false, comments: "As Murakami’s nameless protagonist searches for a mysteriously vanished girlfriend, he is plunged into a wind tunnel of sexual violence and metaphysical dread. In this propulsive novel, featuring a shabby but oracular Sheep Man, one of the most idiosyncratically brilliant writers at work today fuses together science fiction, the hardboiled thriller, and white-hot satire." },
    naomi:          { title: "Naomi",                       author: "Junichiro Tanizaki",  read: false, comments: "When twenty-eight-year-old Joji first lays eyes upon the teenage waitress Naomi, he is instantly smitten by her exotic, almost Western appearance. Determined to transform her into the perfect wife and to whisk her away from the seamy underbelly of post-World War I Tokyo, Joji adopts and ultimately marries Naomi, paying for English and music lessons that promise to mold her into his ideal companion. But as she grows older, Joji discovers that Naomi is far from the naïve girl of his fantasies. And, in Tanizaki’s masterpiece of lurid obsession, passion quickly descends into comically helpless masochism." },
    eoe:            { title: "East of Eden",            author: "John Steinbeck",  read: false, comments: "The masterpiece of Steinbeck’s later years, East of Eden is a sprawling epic in which Steinbeck created his most mesmerizing characters and explored his most enduring themes: the mystery of identity, the inexplicability of love, and the murderous consequences of love’s absence." },
    obscene:        { title: "Obscene Bird of Night",                     author: "Jose Donoso",  read: true, comments: "Deep in a maze of musty, forgotten hallways, Mudito rummages through piles of old newspapers. The mute caretaker of the crumbling former abbey, he is hounded by a coven of ancient witches who are bent on transforming him, bit by bit, into the terrifying imbunche: a twisted monster with all of its orifices sewn up, buried alive in its own body. Once, Mudito walked upright and spoke clearly; once he was the personal assistant to one of Chile’s most powerful politicians, Jerónimo de Azcoitía. Once, he ruled over a palace of monsters, built to shield Jeronimo’s deformed son from any concept of beauty. Once, he plotted with the wise woman Peta Ponce to bed Inés, Jerónimo’s wife. Mudito was Humberto, Jerónimo was strong, Inés was beautiful―once upon a time... Narrated in voices that shift and multiply, The Obscene Bird of Night frets the seams between master and slave, rich and poor, reality and nightmares, man and woman, self and other in a maniacal inquiry into the horrifying transformations that power can wreak on identity." },
    proust:         { title: "In Search of Lost Time, Volume 1: Swann's Way",                      author: "Marcel Proust",  read: false, comments: "Swann's Way is one of the preeminent novels of childhood: a sensitive boy's impressions of his family and neighbors, all brought dazzlingly back to life years later by the taste of a madeleine. It also enfolds the short novel 'Swann in Love,' an incomparable study of sexual jealousy that becomes a crucial part of the vast, unfolding structure of In Search of Lost Time. The first volume of the work that established Proust as one of the finest voices of the modern age—satirical, skeptical, confiding, and endlessly varied in his response to the human condition—Swann's Way also stands on its own as a perfect rendering of a life in art, of the past recreated through memory." },
    mulligan:       { title: "Mulligan Stew",                    author: "Gilbert Sorrentino",  read: false, comments: "Widely regarded as Sorrentino's finest achievement, Mulligan Stew takes as its subject the comic possibilities of the modern literary imagination. As avant-garde novelist Antony Lamont struggles to write a 'new wave murder mystery,' his frustrating emotional and sexual life wreaks havoc on his work-in-progress. As a result, his narrative (the very book we are reading) turns into a literary 'stew' an uproariously funny melange of journal entries, erotic poetry, parodies of all kinds, love letters, interviews, and lists—as Hugh Kenner in Harper's wrote, 'for another such virtuoso of the List you'd have to resurrect Joyce.' Soon, Lamont's characters (on loan from F. Scott Fitzgerald, Flann O'Brien, James Joyce, and Dashiell Hammet) take on lives of their own, completely sabotaging his narrative. Sorrentino has vastly extended the possibilities of what a novel can be in this extraordinary work, which both parodies and pays homage to the art of fiction." },
    ulysses:        { title: "Ulysses",                     author: "James Joyce",  read: false, comments: "Set in Dublin on a single day, June 16, 1904, the novel follows Leopold Bloom, a Jewish advertising agent, as he navigates the city. Interwoven with Bloom’s story are the inner lives of Stephen Dedalus and Molly Bloom, creating a rich tapestry of perspectives and experiences. Inspired by Homer’s Odyssey, Joyce reimagines the epic journey in a modern context, exploring themes of identity, love, and the ordinary heroism of everyday life." },
    underw:         { title: "Underworld",                  author: "Don Delillo",  read: false, comments: "It begins with a moment of legend: the 1951 baseball game between the New York Giants and the Brooklyn Dodgers in which the winning homerun known as the Shot Heard Round the World coincides with news of the Soviet Union’s first hydrogen bomb test. The baseball itself, scuffed and passed from hand to hand, becomes the thread that weaves an astonishing tapestry that spans the Cold War, the Civil Rights Movement, Vietnam protests, and beyond, telling the story of Nick Shay, Klara Sax, and the hidden histories of a nation both haunted and illuminated by its past." },
    foucault:       { title: "Foucault",                    author: "Jacques Derrida",  read: false, comments: "" },
    poetics:        { title: "Poetics",                     author: "Aristotle",  read: true, comments: "In the Poetics, his near-contemporary account of classical Greek tragedy, Aristotle examine the dramatic elements of plot, character, language and spectacle that combine to produce pity and fear in the audience, and asks why we derive pleasure from this apparently painful process. Taking examples from the plays of Aeschylus, Sophocles and Euripides, the Poetics introduced into literary criticism such central concepts as mimesis ('imitation'), hamartia ('error') and katharsis, which have informed serious thinking about drama ever since. Aristotle explains how the most effective tragedies rely on complication and resolution, recognition and reversals, while centring on chaaracerts of heroic stature, idealised yet true to life. One of the most perceptive and influential works of criticism in Western literary history, the Poetics has informed serious thinking about drama ever since." },
    dead:           { title: "The Tibetan Book of the Dead",                        author: "Chogyam Trungpa",  read: false, comments: "As a funerary text and guide to the afterlife, The Tibetan Book of the Dead was read aloud to the dying or recently deceased so that they could recognize the true nature of the mind and thus attain enlightenment and liberation from the suffering associated with the endless cycle of death and rebirth." },
    artoflive:      { title: "The Art of Living",               author: "Epictetus",  read: false, comments: "" },
    madness:        { title: "Madness and Civilization",                     author: "Michel Foucault",  read: true, comments: "Michel Foucault examines the archeology of madness in the West from 1500 to 1800 - from the late Middle Ages, when insanity was still considered part of everyday life and fools and lunatics walked the streets freely, to the time when such people began to be considered a threat, asylums were first built, and walls were erected between the 'insane' and the rest of humanity." },
    hume:           { title: "An Enquiry Concerning Human Understanding",                        author: "David Hume",  read: false, comments: "A landmark of Enlightenment thought, Hume's An Enquiry Concerning Human Understanding is accompanied here by two shorter works that shed light on it: A Letter from a Gentleman to His Friend in Edinburgh, Hume's response to those accusing him of atheism, of advocating extreme skepticism, and of undermining the foundations of morality; and his Abstract of A Treatise of Human Nature, which anticipates discussions developed in the Enquiry." },
    prince:         { title: "The Prince",                  author: "Niccolo Machiavelli",  read: false, comments: "The Prince shocked Europe on publication with its advocacy of ruthless tactics for gaining absolute power and its abandonment of conventional morality. Niccoló Machiavelli drew on his own experience of office under the turbulent Florentine republic, rejecting traditional values of political theory and recognizing the complicated, transient nature of political life. Concerned not with lofty ideal but with a regime that would last, The Prince has become the bible of realpolitik, and it still retains its power to alarm and to instruct. In this edition, Machiavelli's tough-minded and pragmatic Italian is preserved in George Bull's clear, unambiguous translation." },
    discourses:     { title: "The Discourses",                  author: "Niccolo Machiavelli",  read: false, comments: "Few figures in intellectual history have proved as notorious and ambiguous as Niccolò Machiavelli. But while his treatise The Prince made his name synonymous with autocratic ruthlessness and cynical manipulation, The Discourses (c.1517) shows a radically different outlook on the world of politics. In this carefully argued commentary on Livy's history of republican Rome, Machiavelli proposed a system of government that would uphold civic freedom and security by instilling the virtues of active citizenship, and that would also encourage citizens to put the needs of the state above selfish, personal interests. Ambitious in scope, but also clear-eyed and pragmatic, The Discourses creates a modern theory of republic politics." },
    metamorp:       { title: "Metamorphoses",               author: "Ovid",  read: true, comments: "In Metamophoses, Ovid brings together a dazzling array of mythological tales, ingeniously linked by the idea of transformation—often as a result of love or lust—where men and women find themselves magically changed into new and sometimes extraordinary beings. Beginning with the creation of the world and ending with the deification of Augustus, Ovid interweaves many of the best-known myths and legends of ancient Greece and Rome, including Daedalus and Icarus, Pyramus and Thisbe, Pygmalion, Perseus and Andromeda, and the fall of Troy. Erudite but light-hearted, dramatic and yet playful, Metamorphoses has influenced writers and artists throughout the centuries from Shakespeare and Titian to Picasso and Ted Hughes." },
    gorg:           { title: "Gorgias",                     author: "Plato",  read: true, comments: "Taking the form of a dialogue between Socrates, Gorgias, Polus and Callicles, Gorgias debates perennial questions about the nature of government and those who aspire to public office. Are high moral standards essential or should we give our preference to the pragmatist who gets things done or negotiates successfully? Should individuals be motivated by a desire for personal power and prestige, or genuine concern for the moral betterment of the citizens? These questions go to the heart of Athenian democratic principles and are more relevant than ever in today's political climate." },
    nausea:         { title: "Nausea",                      author: "Jean-Paul Sartre",  read: false, comments: "Nausea is the story of Antoine Roquentin, a French writer who is horrified at his own existence. In impressionistic, diary form he ruthlessly catalogs his every feeling and sensation. His thoughts culminate in a pervasive, overpowering feeling of nausea which “spreads at the bottom of the viscous puddle, at the bottom of our time ― the time of purple suspenders and broken chair seats; it is made of wide, soft instants, spreading at the edge, like an oil stain.”" },
    sophocles:      { title: "Sophocles I and II: Tragedies",                   author: "Sophocles",  read: false, comments: "" },
    tao:            { title: "Tao Te Ching",                         author: "Lao Tzu",  read: false, comments: "Traditionally attributed to Lao Tzu, an older contemporary of Confucius (551 - 479 BC), it is now thought that the work was compiled in about the fourth century BC. An anthology of wise sayings, it offers a model by which the individual can live rather than explaining the human place in the universe. The moral code it encourages is based on modesty and self-restraint, and the rewards reaped for such a life are harmony and flow of life." },
    savage:         { title: "The Savage Detectives",                      author: "Roberto Bolaño",  read: true, comments: "National Bestseller In this dazzling novel, the book that established his international reputation, Roberto Bolaño tells the story of two modern-day Quixotes-the last survivors of an underground literary movement, perhaps of literature itself-on a tragicomic quest through a darkening, entropic universe: our own. The Savage Detectives is an exuberant, raunchy, wildly inventive, and ambitious novel from one of the greatest Latin American authors of our age." },
    "2666":         { title: "2666",                        author: "Roberto Bolaño",  read: true, comments: "Composed in the last years of Roberto Bolaño's life, 2666 was greeted across Europe and Latin America as his highest achievement, surpassing even his previous work in its strangeness, beauty, and scope. Its throng of unforgettable characters includes academics and convicts, an American sportswriter, an elusive German novelist, and a teenage student and her widowed, mentally unstable father. Their lives intersect in the urban sprawl of Santa Teresa―a fictional Juárez―on the U.S.-Mexico border, where hundreds of young factory workers, in the novel as in life, have disappeared." },
    borgespoems:    { title: "Selected Poems",                author: "Jorge Luis Borges",  read: false, comments: "Though universally acclaimed for his dazzling fictions, Jorge Luis Borges always considered himself first and foremost a poet. This new bilingual selection brings together some two hundred poems, including scores of poems never previously translated. Edited by Alexander Coleman, it draws from a lifetime's work--from Borges's first published volume of verse, Fervor de Buenos Aires (1923), to his final work, Los conjurados, published just a year before his death in 1986. Throughout this unique collection the brilliance of the Spanish originals is matched by luminous English versions by a remarkable cast of translators, including Robert Fitzgerald, Stephen Kessler, W. S. Merwin, Alastair Reid, Mark Strand, Charles Tomlinson, and John Updike." },
    wuther:         { title: "Wuthering Heights",           author: "Emily Brontë",  read: false, comments: "As darkness falls, a man caught in a snowstorm is forced to shelter at the strange, grim house Wuthering Heights. It is a place he will never forget. There he will come to learn the story of Catherine and Heathcliff: how she was forced to choose between her well-meaning husband and the dangerous man she had loved since she was young. How her choice led to betrayal and terrible revenge - and continues to torment those in the present. How love can transgress authority, convention, even death." },
    masternmarg:    { title: "The Master and Margarita",    author: "Mikhail Bulgakov",  read: false, comments: "Nothing in the whole of literature compares with The Master and Margarita. One spring afternoon, the Devil, trailing fire and chaos in his wake, weaves himself out of the shadows and into Moscow. Mikhail Bulgakov’s fantastical, funny, and devastating satire of Soviet life combines two distinct yet interwoven parts: one set in contemporary Moscow, the other in ancient Jerusalem. Each part is brimming with historical, imaginary, frightful, and wonderful characters. Written during the darkest days of Stalin’s reign, and finally published in 1966 and 1967, The Master and Margarita became a literary phenomenon, signaling artistic and spiritual freedom for Russians everywhere." },
    stranger:       { title: "The Stranger",                author: "Albert Camus",  read: true, comments: "Since it was first published in English, in 1946, Albert Camus’s first novel, The Stranger (L’etranger), has had a profound impact on millions of American readers. Through this story of an ordinary man who unwittingly gets drawn into a senseless murder on a sundrenched Algerian beach, Camus explored what he termed “the nakedness of man faced with the absurd.”" },
    plague:         { title: "The Plague",                  author: "Albert Camus",  read: true, comments: "The townspeople of Oran are in the grip of a deadly plague, which condemns its victims to a swift and horrifying death. Fear, isolation, and claustrophobia follow as they are forced into quarantine. Each person responds in their own way to the lethal disease: some resign themselves to fate, some seek blame, and a few, like Dr. Rieux, resist the terror." },
    exile:          { title: "Exile and the Kingdom",                       author: "Albert Camus",  read: false, comments: "From a variety of masterfully rendered perspectives, these six stories depict people at painful odds with the world around them. A wife can only surrender to a desert night by betraying her husband. An artist struggles to honor his own aspirations as well as society's expectations of him. A missionary brutally converted to the worship of a tribal fetish is left with but an echo of his identity. They display Camus at the height of his powers." },
    journey2:       { title: "Journey to the End of the Night",                  author: "Louis-Ferdinand Céline",  read: false, comments: "Céline’s masterpiece―colloquial, polemic, hyper realistic―boils over with bitter humor and revulsion at society’s idiocy and hypocrisy: Journey to the End of the Night is a literary symphony of cruelty and violence that hurtles through the improbable travels of the petit bourgeois (and largely autobiographical) antihero, Bardamu: from the trenches of WWI, to the African jungle, to New York, to the Ford Factory in Detroit, and finally to life in Paris as a failed doctor. Ralph Manheim’s pitch-perfect translation captures Céline’s savage energy, and a dynamic afterword by William T. Vollmann presents a fresh, furiously alive take on this astonishing novel." },
    deathtax:       { title: "Death on the Installment Plan",             author: "Louis-Ferdinand Céline",  read: false, comments: "Death on the Installment Plan is a companion volume to Louis-Ferdinand Céline’s earlier novel, Journey to the End of the Night. Published in rapid succession in the middle 1930s, these two books shocked European literature and world consciousness. Nominally fiction but more rightly called “creative confessions,” they told of the author’s childhood in excoriating Paris slums, of service in the mud wastes of World War I and African jungles. Mixing unmitigated despair with Gargantuan comedy, they also created a new style, in which invective and obscenity were laced with phrases of unforgettable poetry. Céline’s influence revolutionized the contemporary approach to fiction." },
    hopsc:          { title: "Hopscotch",                   author: "Julio Cortázar",  read: false, comments: "Horacio Oliveira is an Argentinian writer who lives in Paris with his mistress, La Maga, surrounded by a loose-knit circle of bohemian friends who call themselves 'the Club.' A child's death and La Maga's disappearance put an end to his life of empty pleasures and intellectual acrobatics, and prompt Oliveira to return to Buenos Aires, where he works by turns as a salesman, a keeper of a circus cat which can truly count, and an attendant in an insane asylum. Hopscotch is the dazzling, freewheeling account of Oliveira's astonishing adventures." },
    libra:          { title: "Libra",                       author: "Don DeLillo",  read: false, comments: "In this powerful, unsettling novel, Don DeLillo chronicles Lee Harvey Oswald’s odyssey from troubled teenager to a man of precarious stability who imagines himself an agent of history. When “history” presents itself in the form of two disgruntled CIA operatives who decide that an unsuccessful attempt on the life of the president will galvanize the nation against communism, the scales are irrevocably tipped." },
    "white noise":  { title: "White Noise",                 author: "Don DeLillo",  read: false, comments: "Jack Gladney teaches Hitler Studies at a liberal arts college in Middle America where his colleagues include New York expatriates who want to immerse themselves in “American magic and dread.” Jack and his fourth wife, Babette, bound by their love, fear of death, and four ultramodern offspring, navigate the usual rocky passages of family life to the background babble of brand-name consumerism. Then a lethal black chemical cloud floats over their lives, an “airborne toxic event” unleashed by an industrial accident. The menacing cloud is a more urgent and visible version of the “white noise” engulfing the Gladney family—radio transmissions, sirens, microwaves, ultrasonic appliances, and TV murmurings—pulsing with life, yet suggesting something ominous." },
    karam:          { title: "The Brothers Karamazov",      author: "Fyodor Dostoevsky",  read: false, comments: "The Brothers Karamazov is a murder mystery, a courtroom drama, and an exploration of erotic rivalry in a series of triangular love affairs involving the “wicked and sentimental” Fyodor Pavlovich Karamazov and his three sons―the impulsive and sensual Dmitri; the coldly rational Ivan; and the healthy, red-cheeked young novice Alyosha. Through the gripping events of their story, Dostoevsky portrays the whole of Russian life, its social and spiritual striving, in what was both the golden age and a tragic turning point in Russian culture." },
    crimep:         { title: "Crime and Punishment",        author: "Fyodor Dostoevsky",  read: false, comments: "In Crime and Punishment, when Raskolnikov, an impoverished student living in the St. Petersburg of the tsars, commits an act of murder and theft, he sets into motion a story that is almost unequalled in world literature for its excruciating suspense, its atmospheric vividness, and its depth of characterization and vision. Dostoevsky’s drama of sin, guilt, and redemption transforms the sordid story of an old woman’s murder into the nineteenth century’s profoundest and most compelling philosophical novel." },
    demons:         { title: "Demons",                      author: "Fyodor Dostoevsky",  read: false, comments: "Pyotr and Stavrogin are the leaders of a Russian revolutionary cell. Their aim is to overthrow the Tsar, destroy society, and seize power for themselves. Together they train terrorists who are willing to lay down their lives to accomplish their goals. But when the group is threatened with exposure, will their recruits be willing to kill one of their own to cover their tracks? Savage and powerful yet lively and often comic, Demons was inspired by a real-life political murder and is a scathing and eerily prescient indictment of those who use violence to serve their beliefs." },
    nameofrose:     { title: "The Name of the Rose",        author: "Umberto Eco",  read: false, comments: "The year is 1327. Franciscans in a wealthy Italian abbey are suspected of heresy, and Brother William of Baskerville arrives to investigate. But his delicate mission is suddenly overshadowed by seven bizarre deaths that take place in seven days and nights of apocalyptic terror. Brother William turns detective, and a uniquely deft one at that. His tools are the logic of Aristotle, the theology of Aquinas, the empirical insights of Roger Bacon - all sharpened to a glistening edge by his wry humor and ferocious curiosity. He collects evidence, deciphers secret symbols and coded manuscripts, and digs into the eerie labyrinth of the abbey where 'the most interesting things happen at night'." },
    sentence:       { title: "The Sentence",                    author: "Louise Erdrich",  read: false, comments: "Louise Erdrich's latest novel, The Sentence, asks what we owe to the living, the dead, to the reader and to the book. A small independent bookstore in Minneapolis is haunted from November 2019 to November 2020 by the store's most annoying customer. Flora dies on All Souls' Day, but she simply won't leave the store. Tookie, who has landed a job selling books after years of incarceration that she survived by reading 'with murderous attention,' must solve the mystery of this haunting while at the same time trying to understand all that occurs in Minneapolis during a year of grief, astonishment, isolation, and furious reckoning." },
    sept:           { title: "Septology",                   author: "Jon Fosse",  read: false, comments: "What makes us who we are? And why do we lead one life and not another? Asle, an ageing painter and widower who lives alone on the southwest coast of Norway, is reminiscing about his life. His only friends are his neighbour, Åsleik, a traditional fisherman-farmer, and Beyer, a gallerist who lives in the city. There, in Bjørgvin, lives another Asle, also a painter but lonely and consumed by alcohol. Asle and Asle are doppelgängers—two versions of the same person, two versions of the same life, both grappling with existential questions about death, love, light and shadow, faith and hopelessness. The three volumes of Jon Fosse's Septology—The Other Name, I is Another, and A New Name—collected in for the first time in this limited hardcover edition, are a transcendent exploration of the human condition, and a radically other reading experience—incantatory, hypnotic, and utterly unique." },
    recog:          { title: "The Recognitions",            author: "William Gaddis",  read: false, comments: "The Recognitions is a sweeping depiction of a world in which everything that anyone recognizes as beautiful or true or good emerges as anything but: our world. The book is a masquerade, moving from New England to New York to Madrid, from the art world to the underworld, but it centers on the story of Wyatt Gwyon, the son of a New England minister, who forsakes religion to devote himself to painting, only to despair of his inspiration. In expiation, he will paint nothing but flawless copies of his revered old masters—copies, however, that find their way into the hands of a sinister financial wizard by the name of Recktall Brown, who of course sells them as the real thing." },
    dubl:           { title: "Dubliners",                   author: "James Joyce",  read: false, comments: "Living overseas but writing, always, about his native city, Joyce made Dublin unforgettable. The stories in Dubliners show us truants, seducers, gossips, rally-drivers, generous hostesses, corrupt politicians, failing priests, amateur theologians, struggling musicians, moony adolescents, victims of domestic brutishness, sentimental aunts and poets, patriots earnest or cynical, and people striving to get by. In every sense an international figure, Joyce was faithful to his own country by seeing it unflinchingly and challenging every precedent and piety in Irish literature." },
    trial:          { title: "The Trial",                   author: "Franz Kafka",  read: false, comments: "Written in 1914, The Trial is the terrifying tale of Josef K., a respectable bank officer who is suddenly and inexplicably arrested and must defend himself against a charge about which he can get no information. Whether read as an existential tale, a parable, or a prophecy of the excesses of modern bureaucracy wedded to the madness of totalitarianism, Kafka's nightmare has resonated with chilling truth for generations of readers. This new edition is based upon the work of an international team of experts who have restored the text, the sequence of chapters, and their division to create a version that is as close as possible to the way the author left it." },
    snowc:          { title: "Snow Country",                author: "Yasunari Kawabata",  read: false, comments: "At an isolated mountain hot spring, with snow blanketing every surface, Shimamura, a wealthy dilettante meets Komako, a lowly geisha. She gives herself to him fully and without remorse, despite knowing that their passion cannot last and that the affair can have only one outcome. In chronicling the course of this doomed romance, Kawabata has created a story for the ages—a stunning novel dense in implication and exalting in its sadness." },
    karl:           { title: "My Struggle, Volume 1: Childhood and Youth",                        author: "Karl Ove Knausgaard",  read: false, comments: "It has already been anointed a Proustian masterpiece and is the rare work of dazzling literary originality that is intensely, irresistibly readable. Unafraid of the big issues―death, love, art, fear―and yet committed to the intimate details of life as it is lived, My Struggle is an essential work of contemporary literature." },
    lightness:      { title: "The Unbearable Lightness of Being", author: "Milan Kundera", read: false, comments: "In The Unbearable Lightness of Being, acclaimed author Milan Kundera tells the story of two couples: a young woman in love with a man torn between his love for her and his incorrigible womanizing, and one of his mistresses and her humbly faithful lover. In a world in which lives are shaped by irrevocable choices and by fortuitous events, a world in which everything occurs but once, existence seems to lose its substance, its weight. Hence, we feel 'the unbearable lightness of being' not only as the consequence of our pristine actions but also in the public sphere, and the two inevitably intertwine." },
    solitude:       { title: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", read: false, comments: "One Hundred Years of Solitude tells the story of the rise and fall, birth and death of the mythical town of Macondo through the history of the Buendiá family. Inventive, amusing, magnetic, sad and alive with unforgettable men and women—brimming with truth, compassion, and a lyrical magic that strikes the soul—this novel is a masterpiece in the art of fiction." },
    bloodmer:       { title: "Blood Meridian",              author: "Cormac McCarthy",  read: false, comments: "Widely considered one of the finest novels by a living writer, Blood Meridian is an epic tale of the violence and corruption that attended America’s westward expansion, brilliantly subverting the conventions of the Western novel and the mythology of the “Wild West.” Its wounded hero, the Kid, a fourteen-year-old Tennessean, must confront the extraordinary brutality of the Glanton gang, a murderous cadre on an official mission to scalp Indians. Seeming to preside over this nightmarish world is the diabolical Judge Holden, one of the most unforgettable characters in American fiction." },
    templeofgo:     { title: "Temple of the Golden Pavilion", author: "Yukio Mishima", read: false, comments: "Because of the boyhood trauma of seeing his mother make love to another man in the presence of his dying father, Mizoguchi becomes a hopeless stutterer. Taunted by his schoolmates, he feels utterly alone and develops a childhood fascination with Kyoto’s famous Golden Temple. While an acolyte at the temple, he fixates on the structure’s aesthetic perfection and it becomes his one and only object of desire. But as Mizoguchi begins to perceive flaws in the temple, he determines that the only true path to beauty lies in an act of horrific violence. Based on a real incident that occurred in 1950, The Temple of the Golden Pavilion brilliantly portrays the passions and agonies of a young man in postwar Japan, bringing to the subject the erotic imagination and instinct for the dramatic moment that marked Mishima as one of the towering makers of modern fiction." },
    hardboiled:     { title: "Hard-Boiled Wonderland and the End of the World",      author: "Haruki Murakami",  read: false, comments: "Across two parallel narratives, Murakami draws readers into a mind-bending universe in which Lauren Bacall, Bob Dylan, a split-brained data processor, a deranged scientist, his shockingly undemure granddaughter, and various thugs, librarians, and subterranean monsters collide to dazzling effect. What emerges is a hyperkinetic novel that is at once hilariously funny and a deeply serious meditation on the nature and uses of the mind." },
    ada:            { title: "Ada, or Ardor",                         author: "Vladimir Nabokov",  read: false, comments: "This story of a man’s lifelong entanglement with his sister is not only a love story; it manages also to be a fairy tale, an epic, a philosophical treatise on the nature of time, a parody of the history of the novel, and an erotic catalogue. It concludes with an ingeniously sardonic appendix by the author, written under the anagrammatic pseudonym Vivian Darkbloom. Ada, or Ardor, published just after Nabokov’s seventieth birthday, is the supreme work of a virtuosic imagination at white heat." },
    lolita:         { title: "Lolita",                      author: "Vladimir Nabokov",  read: true, comments: "Awe and exhilaration—along with heartbreak and mordant wit—abound in Lolita, which tells the story of the aging Humbert Humbert's obsession for the nymphet Dolores Haze. Lolita is also the story of a hypercivilized European colliding with the cheerful barbarism of postwar America. Most of all, it is a meditation on love—love as outrage and hallucination, madness and transformation." },
    palefire:       { title: "Pale Fire",                   author: "Vladimir Nabokov",  read: true, comments: "An ingeniously constructed parody of detective fiction and learned commentary, Pale Fire offers a cornucopia of deceptive pleasures, at the center of which is a 999-line poem written by the literary genius John Shade just before his death. Surrounding the poem is a foreword and commentary by the demented scholar Charles Kinbote, who interweaves adoring literary analysis with the fantastical tale of an assassin from the land of Zembla in pursuit of a deposed king. Brilliantly constructed and wildly inventive, Vladimir Nabokov's witty novel achieves that rarest of things in literature—perfect tragicomic balance." },
    speakm:         { title: "Speak, Memory",               author: "Vladimir Nabokov",  read: false, comments: "Speak, Memory was first published by Vladimir Nabokov in 1951 as Conclusive Evidence and then assiduously revised and republished in 1966. Nabokov's memoir is a moving account of a loving, civilized family, of adolescent awakenings, flight from Bolshevik terror, education in England, and émigré life in Paris and Berlin. The Nabokovs were eccentric, liberal aristocrats, who lived a life immersed in politics and literature on splendid country estates until their world was swept away by the Russian revolution when the author was eighteen years old. Speak, Memory vividly evokes a vanished past in the inimitable prose of Nabokov at his best." },
    disquiet:       { title: "The Book of Disquiet",        author: "Fernando Pessoa",  read: true, comments: "Published for the first time some fifty years after his death, this unique collection of short, aphoristic paragraphs comprises the 'autobiography' of Bernardo Soares, one of Pessoa's alternate selves. Part intimate diary, part prose poetry, part descriptive narrative, captivatingly translated by Richard Zenith, The Book of Disquiet is one of the greatest works of the twentieth century." },
    atlantis:       { title: "Masters of Atlantis",                    author: "Charles Portis",  read: false, comments: "Lamar Jimmerson is the leader of the Gnomon Society, the international fraternal order dedicated to preserving the arcane wisdom of the lost city of Atlantis. Stationed in France in 1917, Jimmerson comes across a little book crammed with Atlantean puzzles, Egyptian riddles, and extended alchemical metaphors. It's the Codex Pappus - the sacred Gnomon text. Soon he is basking in the lore of lost Atlantis, convinced that his mission on earth is to administer to and extend the ranks of the noble brotherhood." },
    gravity:        { title: "Gravity's Rainbow",           author: "Thomas Pynchon",  read: false, comments: "A few months after the Germans’ secret V-2 rocket bombs begin falling on London, British Intelligence discovers that a map of the city pinpointing the sexual conquests of one Lieutenant Tyrone Slothrop, U.S. Army, corresponds identically to a map showing the V-2 impact sites. The implications of this discovery will launch Slothrop on an amazing journey across war-torn Europe, fleeing an international cabal of military-industrial superpowers, in search of the mysterious Rocket 00000." },
    mason:          { title: "Mason & Dixon",               author: "Thomas Pynchon",  read: false, comments: "Charles Mason (1728-1786) and Jeremiah Dixon (1733-1779) were the British surveyors best remembered for running the boundary between Pennsylvania and Maryland that we know today as the Mason-Dixon Line. Here is their story as re-imagined by Thomas Pynchon, featuring Native Americans and frontier folk, ripped bodices, naval warfare, conspiracies erotic and political, major caffeine abuse. We follow the mismatch'd pair--one rollicking, the other depressive; one Gothic, the other pre-Romantic--from their first journey together to the Cape of Good Hope, to pre-Revolutionary America and back, through the strange yet redemptive turns of fortune in their later lives, on a grand tour of the Enlightenment's dark hemisphere, as they observe and participate in the many opportunities for insanity presented them by the Age of Reason." },
    cancer:         { title: "Cancer Ward",            author: "Aleksandr Solzhenitsyn",  read: false, comments: "Cancer Ward, which has been compared to the masterpiece of another Nobel Prize winner, The Magic Mountain by Thomas Mann, examines the relationship of a group of people in the cancer ward of a provincial Soviet hospital in 1955, two years after Stalin's death. While the experiences of the central character, Oleg Kostoglotov, closely reflect the author's own―Solzhenitsyn became a patient in a cancer ward in the mid-1950s, on his release from a labor camp, and later recovered―the patients, as a group, represent a remarkable cross section of contemporary Russian characters and attitudes, both under normal circumstances and then reexamined at the eleventh hour of illness. A seminal work from one of the most powerful voices in twentieth century literature, Cancer Ward offers an extraordinary portrait of life in the Soviet Union." },
    tristram:       { title: "The Life and Opinions of Tristram Shandy, Gentleman",             author: "Laurence Sterne",  read: false, comments: "Laurence Sterne's great masterpiece of bawdy humour and rich satire defies any attempt to categorize it, with a rich metafictional narrative that might classify it as the first 'postmodern' novel. Part novel, part digression, its gloriously disordered narrative interweaves the birth and life of the unfortunate 'hero' Tristram Shandy, the eccentric philosophy of his father Walter, the amours and military obsessions of Uncle Toby, and a host of other characters, including Dr Slop, Corporal Trim and the parson Yorick. A joyful celebration of the endless possibilities of the art of fiction, Tristram Shandy is also a wry demonstration of its limitations." },
    lightanddark:   { title: "Light and Dark",              author: "Natsume Soseki",  read: false, comments: "Recovering in a clinic following surgery, thirty-year-old Tsuda Yoshio receives visits from a procession of intimates: his coquettish young wife, O-Nobu; his unsparing younger sister, O-Hide, who blames O-Nobu's extravagance for her brother's financial difficulties; his self-deprecating friend, Kobayashi, a ne'er-do-well and troublemaker who might have stepped from the pages of a Dostoevsky novel; and his employer's wife, Madam Yoshikawa, a conniving meddler with a connection to Tsuda that is unknown to the others. Divergent interests create friction among this closely interrelated cast of characters that explodes into scenes of jealousy, rancor, and recrimination that will astonish Western readers conditioned to expect Japanese reticence." },
    botch:          { title: "Botchan",                       author: "Natsume Soseki",  read: false, comments: "A hilarious tale about a young man's rebellion against 'the system' in a country school, Natsume Soseki's Botchan has enjoyed a timeless popularity in Japan. The setting is Japan's deep south, where the author himself spent some time teaching English in a boys' school. Into this conservative world, with its social proprieties and established pecking order, breezes Botchan, down from the big city and with scant respect for either his elders or his noisy young charges. The result is a light, funny, fast-paced novel." },
    "3cornered":    { title: "The Three-Cornered World",      author: "Natsume Soseki",  read: false, comments: "The Three Cornered World is the novelistic expression of the contrast between the Western ethical view of reality and the Eastern ethical view by one of Japan's most beloved authors. Natsume Soseki tells of an artist who retreats to a country resort and becomes involved in a series of mysterious encounters with the owner's daughter. Intricately interwoven with the author's reflections on art and nature, conversations with Zen monks and writers of haiku, are a plethora of unique Japanese characters offering the reader an exquisite 'word painting.'" },
    cat:            { title: "I am a Cat",                         author: "Natsume Soseki",  read: true, comments: "Written over the course of 1904-1906, Soseki Natsume's comic masterpiece, I Am a Cat, satirizes the foolishness of upper-middle class Japanese society during the Meiji era. With acerbic wit and sardonic perspective, it follows the whimsical adventures of a world-weary stray kitten who comments on the follies and foibles of the people around him." },
    oblivion:       { title: "Oblivion: Stories",                    author: "David Foster Wallace",  read: true, comments: "These are worlds undreamt of by any other mind. Only David Foster Wallace could convey a father's desperate loneliness by way of his son's daydreaming through a teacher's homicidal breakdown ('The Soul Is Not a Smithy'). Or could explore the deepest and most hilarious aspects of creativity by delineating the office politics surrounding a magazine profile of an artist who produces miniature sculptures in an anatomically inconceivable way ('The Suffering Channel'). Or capture the ache of love's breakdown in the painfully polite apologies of a man who believes his wife is hallucinating the sound of his snoring ('Oblivion')." },
    lobster:        { title: "Consider The Lobster",                     author: "David Foster Wallace",  read: true, comments: "Do lobsters feel pain? Did Franz Kafka have a funny bone? What is John Updike's deal, anyway? And what happens when adult video starlets meet their fans in person? David Foster Wallace answers these questions and more in essays that are also enthralling narrative adventures. Whether covering the three-ring circus of John McCain's 2000 presidential race, plunging into the wars between dictionary writers, or confronting the World's Largest Lobster Cooker at the annual Maine Lobster Festival, Wallace projects a quality of thought that is uniquely his and a voice as powerful and distinct as any in American letters." },
    broom:          { title: "The Broom of the System",         author: "David Foster Wallace",  read: true, comments: "Considered the black sheep of his ouevre since he wrote it at 25, I found it extremely funny and charming though." },
    girlwithcurious:{ title: "Girl with Curious Hair",      author: "David Foster Wallace",  read: true, comments: "Girl with Curious Hair is replete with David Foster Wallace's remarkable and unsettling reimaginations of reality. From the eerily "real," almost holographic evocations of historical figures like Lyndon Johnson and overtelevised game-show hosts and late-night comedians to the title story, where terminal punk nihilism meets Young Republicanism, Wallace renders the incredible comprehensible, the bizarre normal, the absurd hilarious, the familiar strange." },
    allegra:        { title: "Allegra, 24 Hours, fexofenadine HCI 180mg",                     author: "",  read: false, comments: "Why did you even click this?" },
    "lost city":    { title: "Lost City Books Bookmark",                   author: "",  read: false, comments: "My favorite bookstore!" },
  };
  
  const sidebar     = document.getElementById('sidebar');
  const backdrop    = document.getElementById('backdrop');
  const closeBtn    = document.getElementById('close-btn');
  const bookTitle    = document.getElementById('book-title');
  const bookAuthor   = document.getElementById('book-author');
  const bookRead     = document.getElementById('book-read');
  const bookComments = document.getElementById('book-comments');
  const mapWrapper  = document.querySelector('.map-wrapper');
  
  // fix imagemap scaling!!
  
  function rescaleMap() {
    const img = document.querySelector('img[usemap]');
    const areas = document.querySelectorAll('area');
  
    const scaleX = img.offsetWidth / img.naturalWidth;
    const scaleY = img.offsetHeight / img.naturalHeight;
  
    areas.forEach(area => {
      const original = area.getAttribute('data-original-coords') || area.getAttribute('coords');
      area.setAttribute('data-original-coords', original); // cache original on first run
  
      const scaled = original.split(',').map((val, i) =>
        Math.round(i % 2 === 0 ? val * scaleX : val * scaleY)
      ).join(',');
  
      area.setAttribute('coords', scaled);
    });
  }
  
  window.addEventListener('load', rescaleMap);
  window.addEventListener('resize', rescaleMap);

  function openSidebar(key) {
    const book = books[key];
    if (!book) return;
  
    bookTitle.textContent    = book.title    || key;
    bookAuthor.textContent   = book.author   || '';
    bookRead.checked         = book.read     || false;
    bookComments.textContent = book.comments || '';
  
    bookAuthor.style.display   = book.author ? 'inline-block' : 'none';
    bookComments.style.display = book.comments ? 'block' : 'none';
  
    sidebar.classList.add('open');
    backdrop.classList.add('active');
    mapWrapper.classList.add('shifted');
  }
  
  function closeSidebar() {
    sidebar.classList.remove('open');
    backdrop.classList.remove('active');
    mapWrapper.classList.remove('shifted');
  }
  
  
// image map wiring, thank god for that website
  document.querySelectorAll('area[data-book]').forEach(area => {
    area.addEventListener('click', e => {
      e.preventDefault();
      const key = area.getAttribute('data-book');
      openSidebar(key);
    });
  });
  
  closeBtn.addEventListener('click', closeSidebar);
  backdrop.addEventListener('click', closeSidebar);
  
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeSidebar();

  });

